# Generated by assistant to add default users
from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_default_users(apps, schema_editor):
    """Create default admin, landlord and tenant users (idempotent)."""
    User = apps.get_model('api', 'User')
    Tenant = apps.get_model('api', 'Tenant')

    # Admin user
    if not User.objects.filter(username='admin').exists():
        admin = User(
            username='admin',
            email='admin@test.com',
            role='admin',
            is_staff=True,
            is_superuser=True,
            is_active=True,
        )
        # Hash the password directly because historical models may not have set_password
        admin.password = make_password('admin123')
        admin.save()

    # Landlord user
    if not User.objects.filter(username='landlord1').exists():
        landlord = User(
            username='landlord1',
            email='landlord1@test.com',
            role='landlord',
            is_staff=False,
            is_superuser=False,
            is_active=True,
        )
        landlord.password = make_password('landlord123')
        landlord.save()

    # Tenant user + Tenant profile
    if not User.objects.filter(username='tenant1').exists():
        tenant_user = User(
            username='tenant1',
            email='tenant1@test.com',
            role='tenant',
            is_staff=False,
            is_superuser=False,
            is_active=True,
        )
        tenant_user.password = make_password('tenant123')
        tenant_user.save()
        # create tenant profile (Tenant.phone is required)
        try:
            Tenant.objects.create(user=tenant_user, phone='0000000000')
        except Exception:
            # If Tenant model/table isn't available for some reason, ignore
            pass


def delete_default_users(apps, schema_editor):
    """Reverse operation: delete the seeded users and tenant profile."""
    User = apps.get_model('api', 'User')
    Tenant = apps.get_model('api', 'Tenant')

    # Remove tenant profile if exists
    try:
        user = User.objects.filter(username='tenant1').first()
        if user:
            Tenant.objects.filter(user=user).delete()
    except Exception:
        pass

    # Delete users if present
    for username in ('admin', 'landlord1', 'tenant1'):
        try:
            user = User.objects.filter(username=username).first()
            if user:
                user.delete()
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_users, reverse_code=delete_default_users),
    ]
